version: "3.8"
services:
  devcontainer-service:
    build:
      context: ../
      dockerfile: .devcontainer/node/Dockerfile
    image: devcontainer-initial-gantt-task-react-custom:latest
    command: sleep infinity
    env_file:
      - ../.env # initializeCommand creates this file if it is missing
    volumes:
      - ../:/workspace
    restart: unless-stopped
